In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("/content/diabetes.csv")

In [4]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [14]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [15]:
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [17]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler

In [19]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [20]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1    )

In [22]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [23]:
model=Sequential()
model.add(Dense(32,activation="relu",input_dim=8))
model.add(Dense(1,activation="sigmoid"))
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [24]:
model.fit(X_train,y_train,batch_size=32,epochs=100,validation_data=(X_test,y_test) )

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.3636 - loss: 46.1133 - val_accuracy: 0.3571 - val_loss: 31.6930
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3319 - loss: 28.9339 - val_accuracy: 0.3571 - val_loss: 13.0671
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3443 - loss: 10.5491 - val_accuracy: 0.6104 - val_loss: 3.3429
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5287 - loss: 3.5714 - val_accuracy: 0.5455 - val_loss: 2.5096
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4675 - loss: 2.4668 - val_accuracy: 0.5260 - val_loss: 2.4295
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5419 - loss: 2.0916 - val_accuracy: 0.5195 - val_loss: 1.9953
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5059 - loss: 1.9105 - val_accuracy: 0.5325 - val_loss: 1.8143
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5542 - loss: 1.4140 - val_accuracy: 0.5260 - val_loss: 1.6263
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5610 - loss: 1.3442 - val_accuracy: 0.4481 - val_loss: 1.5232
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5344 - loss: 1.3210 - val_accuracy: 0.5130 - val_loss: 1.3687
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5737 - loss: 1.0678 - val_accuracy: 0.4935 - val_loss: 1.2717
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6305 - loss: 0.9597 - val_accuracy: 0.4481 - val_loss: 1.2281
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5508 - loss: 1.0154 - val_accuracy: 0.5390 - val_loss: 1.1452
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6325 - loss: 0.8943 - val_accuracy: 0.5844 - val_loss: 1.1389
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6463 - loss: 0.9483 - val_accuracy: 0.5844 - val_loss: 1.0510
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6092 - loss: 0.8930 - val_accuracy: 0.5779 - val_loss: 1.0473
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6368 - loss: 0.8164 - val_accuracy: 0.5909 - val_loss: 0.9729
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6496 - loss: 0.7675 - val_accuracy: 0.6039 - val_loss: 0.9447
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6936 - loss: 0.7035 - val_accuracy: 0.5974 - val_loss: 0.9090
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6664 - loss: 0.7170 - val_accuracy: 0.6688 - val_loss: 0.8943
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6777 - loss: 0.7170 - val_accuracy: 0.6558 - val_loss: 0.8635
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6973 - loss: 0.6655 - val_accuracy: 0.5974 - val_loss: 0.8569
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6761 - loss: 0.6283 - val_accuracy: 0.5779 - val_loss: 0.8870
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6648 - loss: 0.6907 - val_accuracy: 0.6299 - val_loss: 0.9023
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6764 - loss: 0.6515 - val_accuracy: 0.5714 - val_loss: 0.8719
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6688 - loss: 0.6757 - val_accuracy: 0.6883 - val_loss: 0.8404
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6992 - loss: 0.6186 - val_accuracy: 0.5909 - val_loss: 0.8194
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7022 - loss: 0.5966 - val_accuracy: 0.6234 - val_loss: 0.8141
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6806 - loss: 0.6434 - val_accuracy: 0.6364 - val_loss: 0.8044
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6773 - loss: 0.6316 - val_accuracy: 0.6494 - val_loss: 0.8224
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6832 - loss: 0.5981 - val_accuracy: 0.6234 - val_loss: 0.8513
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7071 - loss: 0.6160 - val_accuracy: 0.7078 - val_loss: 0.8060
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7414 - loss: 0.5754 - val_accuracy: 0.6494 - val_loss: 0.7884
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7210 - loss: 0.6218 - val_accuracy: 0.6948 - val_loss: 0.7762
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7240 - loss: 0.5585 - val_accuracy: 0.6623 - val_loss: 0.7639
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7054 - loss: 0.5839 - val_accuracy: 0.6558 - val_loss: 0.7619
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7301 - loss: 0.5653 - val_accuracy: 0.6558 - val_loss: 0.7907
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7310 - loss: 0.5562 - val_accuracy: 0.5714 - val_loss: 0.8700
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7044 - loss: 0.6105 - val_accuracy: 0.6753 - val_loss: 0.7803
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6834 - loss: 0.6174 - val_accuracy: 0.6169 - val_loss: 0.7801
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7236 - loss: 0.5586 - val_accuracy: 0.6883 - val_loss: 0.7542
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7086 - loss: 0.6192 - val_accuracy: 0.5844 - val_loss: 0.8287
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6660 - loss: 0.6558 - val_accuracy: 0.6883 - val_loss: 0.7687
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7213 - loss: 0.5914 - val_accuracy: 0.6948 - val_loss: 0.7346
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7537 - loss: 0.5281 - val_accuracy: 0.6753 - val_loss: 0.7876
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7035 - loss: 0.6346 - val_accuracy: 0.6039 - val_loss: 0.7983
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7184 - loss: 0.5756 - val_accuracy: 0.7078 - val_loss: 0.7326
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6882 - loss: 0.5970 - val_accuracy: 0.6169 - val_loss: 0.7778
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6796 - loss: 0.6009 - val_accuracy: 0.6883 - val_loss: 0.7267
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7068 - loss: 0.5732 - val_accuracy: 0.6688 - val_loss: 0.7587
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7103 - loss: 0.6088 - val_accuracy: 0.6688 - val_loss: 0.7302
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6885 - loss: 0.5740 - val_accuracy: 0.7013 - val_loss: 0.7285
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7046 - loss: 0.5734 - val_accuracy: 0.7013 - val_loss: 0.7114
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6982 - loss: 0.5974 - val_accuracy: 0.6688 - val_loss: 0.7176
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7173 - loss: 0.5768 - val_accuracy: 0.6688 - val_loss: 0.7244
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6718 - loss: 0.6384 - val_accuracy: 0.7078 - val_loss: 0.7474
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7141 - loss: 0.5686 - val_accuracy: 0.6818 - val_loss: 0.7250
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7312 - loss: 0.5616 - val_accuracy: 0.7208 - val_loss: 0.7178
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7453 - loss: 0.5263 - val_accuracy: 0.7208 - val_loss: 0.7213
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7207 - loss: 0.5630 - val_accuracy: 0.6688 - val_loss: 0.7253
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7219 - loss: 0.5689 - val_accuracy: 0.6234 - val_loss: 0.7584
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7463 - loss: 0.5524 - val_accuracy: 0.6623 - val_loss: 0.8882
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6776 - loss: 0.6908 - val_accuracy: 0.6883 - val_loss: 0.7248
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7437 - loss: 0.5353 - val_accuracy: 0.6688 - val_loss: 0.8854
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6570 - loss: 0.6455 - val_accuracy: 0.6818 - val_loss: 0.8271
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7291 - loss: 0.5872 - val_accuracy: 0.6883 - val_loss: 0.7220
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7179 - loss: 0.5507 - val_accuracy: 0.7338 - val_loss: 0.7314
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7146 - loss: 0.5463 - val_accuracy: 0.6623 - val_loss: 0.7055
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7197 - loss: 0.5519 - val_accuracy: 0.7013 - val_loss: 0.7268
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7408 - loss: 0.5353 - val_accuracy: 0.6753 - val_loss: 0.7965
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7204 - loss: 0.6085 - val_accuracy: 0.5844 - val_loss: 0.8441
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6890 - loss: 0.6064 - val_accuracy: 0.6753 - val_loss: 0.7189
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6870 - loss: 0.5663 - val_accuracy: 0.6948 - val_loss: 0.7356
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7363 - loss: 0.5393 - val_accuracy: 0.7403 - val_loss: 0.7075
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7161 - loss: 0.5292 - val_accuracy: 0.6948 - val_loss: 0.7251
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7551 - loss: 0.5156 - val_accuracy: 0.6883 - val_loss: 0.7036
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7419 - loss: 0.5196 - val_accuracy: 0.7273 - val_loss: 0.7393
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7417 - loss: 0.5586 - val_accuracy: 0.6494 - val_loss: 0.7800
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7338 - loss: 0.5403 - val_accuracy: 0.7403 - val_loss: 0.7134
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4948 - val_accuracy: 0.6948 - val_loss: 0.7312
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7607 - loss: 0.5165 - val_accuracy: 0.7078 - val_loss: 0.7199
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7550 - loss: 0.5089 - val_accuracy: 0.7273 - val_loss: 0.7190
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7197 - loss: 0.4991 - val_accuracy: 0.6818 - val_loss: 0.7328
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7278 - loss: 0.5629 - val_accuracy: 0.7013 - val_loss: 0.7834
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7148 - loss: 0.5832 - val_accuracy: 0.6818 - val_loss: 0.7481
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7217 - loss: 0.5619 - val_accuracy: 0.7143 - val_loss: 0.7105
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7246 - loss: 0.5107 - val_accuracy: 0.6818 - val_loss: 0.7659
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7365 - loss: 0.5168 - val_accuracy: 0.7013 - val_loss: 0.8110
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7062 - loss: 0.5390 - val_accuracy: 0.6948 - val_loss: 0.7194
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7534 - loss: 0.5187 - val_accuracy: 0.7143 - val_loss: 0.7282
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7052 - loss: 0.6089 - val_accuracy: 0.6948 - val_loss: 0.7661
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7253 - loss: 0.5410 - val_accuracy: 0.6753 - val_loss: 0.7472
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7340 - loss: 0.5249 - val_accuracy: 0.6818 - val_loss: 0.7616
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6891 - loss: 0.6160 - val_accuracy: 0.6169 - val_loss: 0.8129
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7247 - loss: 0.5754 - val_accuracy: 0.6948 - val_loss: 0.7278
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7336 - loss: 0.5288 - val_accuracy: 0.7403 - val_loss: 0.7278
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7212 - loss: 0.5425 - val_accuracy: 0.7013 - val_loss: 0.7608
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7557 - loss: 0.4925 - val_accuracy: 0.7143 - val_loss: 0.7426
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7148 - loss: 0.5507 - val_accuracy: 0.7208 - val_loss: 0.7261
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7049 - loss: 0.5860 - val_accuracy: 0.6558 - val_loss: 0.7682

In [26]:
!pip install keras-tuner
import kerastuner as kt

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.76.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.15.1)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.18.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.1.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 4.4 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

/tmp/ipython-input-1657191961.py:2: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [43]:
def build_model(hp):
    model=Sequential()
    model.add(Dense(32,activation="relu",input_dim=8))
    model.add(Dense(1,activation="sigmoid"))
    optimizer = hp.Choice('optimizer',values=['sgd', 'adam', 'rmsprop', 'adadelta'])



    model.compile(loss="binary_crossentropy",optimizer=optimizer,metrics=["accuracy"])
    return model

In [41]:
tuner=kt.RandomSearch(build_model,objective="val_accuracy",max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [37]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test,y_test))

In [44]:
## to know best optimizer
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'sgd'}

In [47]:

model=tuner.get_best_models(num_models=1)[0]

In [48]:
model.fit(X_train,y_train,epochs=100,batch_size=32,initial_epoch=6,validation_data=(X_test,y_test   ))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6338 - loss: 0.7050 - val_accuracy: 0.5844 - val_loss: 0.7348
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6835 - loss: 0.6304 - val_accuracy: 0.6688 - val_loss: 0.7312
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6724 - loss: 0.6151 - val_accuracy: 0.6558 - val_loss: 0.6827
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6312 - loss: 0.6591 - val_accuracy: 0.6688 - val_loss: 0.7252
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6533 - loss: 0.6162 - val_accuracy: 0.6494 - val_loss: 1.0128
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6840 - loss: 0.6136 - val_accuracy: 0.6364 - val_loss: 0.7919
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7062 - loss: 0.5901 - val_accuracy: 0.6299 - val_loss: 0.7301
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6834 - loss: 0.6041 - val_accuracy: 0.6299 - val_loss: 0.9063
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6991 - loss: 0.5603 - val_accuracy: 0.6558 - val_loss: 0.6853
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6777 - loss: 0.5898 - val_accuracy: 0.6558 - val_loss: 0.8564
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6508 - loss: 0.6584 - val_accuracy: 0.6753 - val_loss: 0.6749
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6841 - loss: 0.6355 - val_accuracy: 0.6364 - val_loss: 0.7227
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6712 - loss: 0.5981 - val_accuracy: 0.6494 - val_loss: 0.6608
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7273 - loss: 0.5723 - val_accuracy: 0.4351 - val_loss: 1.1392
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5960 - loss: 0.7565 - val_accuracy: 0.6169 - val_loss: 0.7116
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6888 - loss: 0.6131 - val_accuracy: 0.6494 - val_loss: 0.7516
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7143 - loss: 0.5908 - val_accuracy: 0.6234 - val_loss: 0.6863
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7297 - loss: 0.5686 - val_accuracy: 0.6753 - val_loss: 0.6539
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6747 - loss: 0.6033 - val_accuracy: 0.6753 - val_loss: 0.6511
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6796 - loss: 0.5790 - val_accuracy: 0.6494 - val_loss: 0.6857
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6722 - loss: 0.5897 - val_accuracy: 0.6558 - val_loss: 0.7670
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7124 - loss: 0.6148 - val_accuracy: 0.6883 - val_loss: 0.7042
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6778 - loss: 0.6049 - val_accuracy: 0.6494 - val_loss: 0.6988
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6693 - loss: 0.6327 - val_accuracy: 0.6688 - val_loss: 0.6915
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7151 - loss: 0.5872 - val_accuracy: 0.6883 - val_loss: 0.6579
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6984 - loss: 0.5781 - val_accuracy: 0.6623 - val_loss: 0.6611
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7087 - loss: 0.5686 - val_accuracy: 0.6623 - val_loss: 0.6724
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6843 - loss: 0.5855 - val_accuracy: 0.6753 - val_loss: 0.7820
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6842 - loss: 0.6113 - val_accuracy: 0.5649 - val_loss: 0.7540
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6673 - loss: 0.5910 - val_accuracy: 0.6623 - val_loss: 0.6801
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6751 - loss: 0.5958 - val_accuracy: 0.6299 - val_loss: 0.6783
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6691 - loss: 0.5944 - val_accuracy: 0.6948 - val_loss: 0.6819
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7052 - loss: 0.5939 - val_accuracy: 0.6623 - val_loss: 0.7140
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6770 - loss: 0.5861 - val_accuracy: 0.6688 - val_loss: 0.7163
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6744 - loss: 0.5778 - val_accuracy: 0.6234 - val_loss: 0.6928
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6900 - loss: 0.5759 - val_accuracy: 0.6494 - val_loss: 0.6920
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6972 - loss: 0.5871 - val_accuracy: 0.6494 - val_loss: 0.6577
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7194 - loss: 0.5688 - val_accuracy: 0.6429 - val_loss: 0.6597
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7062 - loss: 0.5832 - val_accuracy: 0.6429 - val_loss: 0.7700
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7271 - loss: 0.5617 - val_accuracy: 0.6494 - val_loss: 0.6759
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6877 - loss: 0.5840 - val_accuracy: 0.6623 - val_loss: 0.6665
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7004 - loss: 0.5893 - val_accuracy: 0.6883 - val_loss: 0.6895
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7189 - loss: 0.5781 - val_accuracy: 0.6104 - val_loss: 0.6846
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6947 - loss: 0.5885 - val_accuracy: 0.6688 - val_loss: 0.6968
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6811 - loss: 0.6210 - val_accuracy: 0.6039 - val_loss: 0.7126
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6969 - loss: 0.5772 - val_accuracy: 0.6948 - val_loss: 0.7280
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7033 - loss: 0.5667 - val_accuracy: 0.5584 - val_loss: 0.7604
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6694 - loss: 0.5960 - val_accuracy: 0.6623 - val_loss: 0.7871
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6992 - loss: 0.5965 - val_accuracy: 0.6753 - val_loss: 0.7439
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7468 - loss: 0.5491 - val_accuracy: 0.5000 - val_loss: 0.8558
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6864 - loss: 0.5822 - val_accuracy: 0.6558 - val_loss: 0.6642
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6860 - loss: 0.5626 - val_accuracy: 0.6558 - val_loss: 0.6615
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7045 - loss: 0.5585 - val_accuracy: 0.6623 - val_loss: 0.7648
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6991 - loss: 0.5840 - val_accuracy: 0.6688 - val_loss: 0.8652
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7069 - loss: 0.6000 - val_accuracy: 0.6364 - val_loss: 0.6917
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7085 - loss: 0.5815 - val_accuracy: 0.6688 - val_loss: 0.6730
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7119 - loss: 0.5653 - val_accuracy: 0.6623 - val_loss: 0.8575
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7076 - loss: 0.5955 - val_accuracy: 0.6429 - val_loss: 0.6905
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6970 - loss: 0.5802 - val_accuracy: 0.6883 - val_loss: 0.6829
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7087 - loss: 0.5627 - val_accuracy: 0.6753 - val_loss: 0.6755
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7159 - loss: 0.5464 - val_accuracy: 0.6623 - val_loss: 0.7851
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6903 - loss: 0.5687 - val_accuracy: 0.6494 - val_loss: 0.9144
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6841 - loss: 0.6523 - val_accuracy: 0.6623 - val_loss: 0.6829
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7063 - loss: 0.5524 - val_accuracy: 0.6948 - val_loss: 0.7197
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7155 - loss: 0.5784 - val_accuracy: 0.6753 - val_loss: 0.6864
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7219 - loss: 0.5712 - val_accuracy: 0.6429 - val_loss: 0.7440
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6830 - loss: 0.6013 - val_accuracy: 0.5130 - val_loss: 0.7398
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6461 - loss: 0.6111 - val_accuracy: 0.6948 - val_loss: 0.6761
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7069 - loss: 0.5690 - val_accuracy: 0.6299 - val_loss: 0.6637
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7339 - loss: 0.5625 - val_accuracy: 0.6623 - val_loss: 0.6986
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7338 - loss: 0.5430 - val_accuracy: 0.6623 - val_loss: 0.6386
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7186 - loss: 0.5584 - val_accuracy: 0.6623 - val_loss: 0.7905
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7063 - loss: 0.5816 - val_accuracy: 0.6818 - val_loss: 0.7642
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6944 - loss: 0.5943 - val_accuracy: 0.6558 - val_loss: 0.7749
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7273 - loss: 0.5565 - val_accuracy: 0.6818 - val_loss: 0.6504
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6859 - loss: 0.5740 - val_accuracy: 0.6818 - val_loss: 0.6733
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7168 - loss: 0.5691 - val_accuracy: 0.6429 - val_loss: 0.6685
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6894 - loss: 0.5906 - val_accuracy: 0.6818 - val_loss: 0.6559
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7285 - loss: 0.5526 - val_accuracy: 0.6039 - val_loss: 0.6991
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6977 - loss: 0.5614 - val_accuracy: 0.6623 - val_loss: 0.6937
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7107 - loss: 0.5462 - val_accuracy: 0.6818 - val_loss: 0.7027
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7139 - loss: 0.5798 - val_accuracy: 0.6688 - val_loss: 0.7206
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7060 - loss: 0.5576 - val_accuracy: 0.5909 - val_loss: 0.7383
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6576 - loss: 0.6136 - val_accuracy: 0.6883 - val_loss: 0.6700
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7267 - loss: 0.5401 - val_accuracy: 0.6818 - val_loss: 0.6757
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7155 - loss: 0.5368 - val_accuracy: 0.6429 - val_loss: 0.7567
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6818 - loss: 0.5945 - val_accuracy: 0.6883 - val_loss: 0.6986
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6962 - loss: 0.5628 - val_accuracy: 0.6688 - val_loss: 0.6744
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6982 - loss: 0.5826 - val_accuracy: 0.6688 - val_loss: 0.6984
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7136 - loss: 0.5650 - val_accuracy: 0.6753 - val_loss: 0.7466
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7265 - loss: 0.5491 - val_accuracy: 0.6818 - val_loss: 0.7331
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7495 - loss: 0.5167 - val_accuracy: 0.6753 - val_loss: 0.6857
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7438 - loss: 0.5443 - val_accuracy: 0.6623 - val_loss: 0.6630
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7127 - loss: 0.5619 - val_accuracy: 0.6558 - val_loss: 0.6660